"""again with serilization

Revision ID: 842bc4b472a4
Revises: 2fc4089efdc9
Create Date: 2023-11-02 09:47:00.017669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842bc4b472a4'
down_revision = '2fc4089efdc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('time_posted', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('image_thumbnail', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.drop_column('is_published')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('username', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('username', ['username'])

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('video_url')
        batch_op.drop_column('image_thumbnail')
        batch_op.drop_column('time_posted')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
