"""Update models

Revision ID: ccdf021dafe4
Revises: 
Create Date: 2023-11-02 12:26:01.329043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdf021dafe4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=True))
        batch_op.alter_column('is_flagged',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('content_type')
        batch_op.drop_column('rating')
        batch_op.drop_column('time_posted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_posted', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('is_flagged',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('average_rating')

    # ### end Alembic commands ###
